apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsnmicroservices
  namespace: kubernetes-cluster-{{USER_NAME}}
  labels:
    app: app_{{USER_NAME}}
spec:
  selector:
    matchLabels:
      app: app-{{USER_NAME}}
  replicas: 3
  template:
    metadata:
      labels:
        app: app-{{USER_NAME}}
    spec:
      containers:
      - name: app-{{USER_NAME}}
        image: {{USER_NAME}}/i-{{USER_NAME}}-{{BRANCH_NAME}}:latest
        env:
          - name: deployment.branch
            value: {{BRANCH_NAME}} 
        resources:
          limits:
            memory: "128Mi"
            cpu: "30m"
        ports:
        - containerPort: 7100
---
apiVersion: v1
kind: Service
metadata:
  namespace: kubernetes-cluster-{{USER_NAME}}
  name: app-{{USER_NAME}}
spec:
  type: LoadBalancer
  selector:
    app: app-{{USER_NAME}}
  ports:
  - port: {{PORT}}
    targetPort: 7100
    protocol: TCP